### ISSUE TITLE
Configuration Of AzureKinectBodyTracker

### ISSUE THREAD

**Issue by HaipingLe** [microsoft/psi-samples#17]
Hello Microsoft Guys，
We have a very powerful HPC with a powerful Nvidia GPU（RTX 3080 ti).
When running the sample of What's that,  we set TrackerProcessingMode as Cuda but the performance is not perefect.
Is it possible to use TensroRT in this sample?  If so, do you have related experiences?

**Comment by HaipingLe** [comment]
I

**Comment by sandrist** [comment]
I see you closed the issue. Does that mean you figured out how to use TensorRT with the sample? Any learnings you can share?

**Comment by HaipingLe** [comment]
@Sandrist，
I'm  sorry that I closed the issue by mistake.

We can run the sample with Cuda after we introduce body trackink SDK V1.1.0 .
After then I have introduced the TensorRT related DLLs into our project and there will be an unhandled exception.

=================================Exception ==========================================
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
==================================================================================

This kind of exception will occur when we run the sample with CUDA within half an hour.  But it will occur immediately when using tensorRT. 

====================================Stack Trace ==================================
at Microsoft.Azure.Kinect.BodyTracking.Native.NativeMethods.k4abt_tracker_create(Calibration& sensorCalibration, TrackerConfiguration& config, k4abt_tracker_t& tracker)
at Microsoft.Azure.Kinect.BodyTracking.Tracker.Create(Calibration calibration, TrackerConfiguration configuration) in C:\source\src\csharp\Microsoft.Azure.Kinect.BodyTracking\Tracker.cs:line 29
at Microsoft.Psi.AzureKinect.AzureKinectBodyTracker.InitializeTracker(Calibration calibration)
at Microsoft.Psi.AzureKinect.AzureKinectBodyTracker.ReceiveCalibration(Calibration calibration, Envelope envelope)
at Microsoft.Psi.Pipeline.<>c__DisplayClass102_0`1.<CreateReceiver>b__0(Message`1 m)
at Microsoft.Psi.Executive.PipelineElement.<>c__DisplayClass43_1`1.<TrackStateObjectOnContext>b__1()
at Microsoft.Psi.Receiver`1.<>c__DisplayClass13_0.<.ctor>b__0(Message`1 m)
at Microsoft.Psi.Receiver`1.DeliverNext()
at Microsoft.Psi.Scheduling.Scheduler.ExecuteAndRelease(SynchronizationLock synchronizationObject, Action action, SchedulerContext context)
at Microsoft.Psi.Scheduling.Scheduler.Run(Object workItem)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by xiangzhi** [comment]
@HaipingLe The `System.AccessViolationException` has been a constant problem for me in the past and I have not found a satisfying solution. I tried looking for a solution on the SDK github and wasn't able to find any. The problem lies somewhere deep down in the proprietary Microsoft code. 

I did narrow down the problem to me using multiple Azure Kinects on a single graphic card (GTX 1080ti).  I never tried TensorRT, but one thing I suggest you can try is to write a C++ program with the BodyTracking SDK without Psi and see if you have the same problem. Doing that at least let you see if it is a fundamental BodyTracking SDK problem or a Psi problem.
 
For my application, I end up just running the body tracker by itself in a separate process and restart the process when it failed after X minutes.

**Comment by HaipingLe** [comment]
@xiangzhi，
Thanks for your suggestion!

**Comment by thundercarrot** [comment]
The problem seems to be a code defect in k4abt.dll. I put some code together to patch the problem after the .dll is loaded. Call this early in your process. My hunch is that this problem appears due to recent changes in how Windows allocates memory.
```
#include <windows.h>
#include <stdint.h>

BOOL Patch(HMODULE module, uint8_t* address, const uint8_t* expected, const uint8_t* patched, size_t size)
{
	if (memcmp(address, expected, size) != 0)
		return FALSE;
	DWORD oldProtection;
	if (!VirtualProtect(address, size, PAGE_EXECUTE_READWRITE, &oldProtection))
		return FALSE;
	memcpy(address, patched, size);
	FlushInstructionCache(GetCurrentProcess(), address, size);
	DWORD ignored;
	VirtualProtect(address, size, oldProtection, &ignored);
	return TRUE;
}

// patches a code defect in Azure Kinect Body Tracking SDK v1.1.2 that causes an intermittent crash on Windows 11
BOOL Patch_k4abt()
{
	HMODULE module = GetModuleHandleW(L"k4abt.dll");
	if (!module)
		return FALSE;

	const uint8_t expectedLea[] = { 0x48, 0x8D, 0x47, 0xFF }; // lea rax,[rdi-1]
	const uint8_t patchedLea[] = { 0x48, 0x8D, 0x47, 0xFE }; // lea rax,[rdi-2]
	if (!Patch(module, (uint8_t*)module + 0x297856, expectedLea, patchedLea, sizeof(expectedLea)))
		return FALSE;

	const uint8_t expectedDec[] = { 0x48, 0xFF, 0xC8 }; // dec rax
	// 64 bit rax and and 32 bit eax registers are aliased
	// upper 32 bit of rax are cleared; this is ok for 32 bit values and fits in 3 bytes:
	const uint8_t patchedDec[] = { 0x83, 0xE8, 0x02 }; // sub eax,2 
	if (!Patch(module, (uint8_t*)module + 0x29786A, expectedDec, patchedDec, sizeof(expectedDec)))
		return FALSE;
	
	return TRUE;
}
```
